simulation:
  dt: 0.00416
  gravity: -9.81
  physics_client: "GUI"

agents:
  # LEADER
  - type: "uav"
    name: "drone_0"
    urdf_path: "assets/quadrotor.urdf"
    start_pos: [0.0, 0.0, 0.5]
    waypoints:
      - [0.0, 0.0, 2.0]
      - [5.0, 0.0, 2.0]
      - [5.0, 5.0, 2.5]
      - [0.0, 5.0, 2.0]
      - [0.0, 0.0, 1.0]
    logging: {enabled: true, dir: "logs", file: "drone_0_log.csv"}
    
    acc_limit_xy: 3.0
    sensors:
      gps: {enabled: true, position_noise_std: 0.1, velocity_noise_std: 0.05}
      imu: {enabled: true, accel_noise_std: 0.1, gyro_noise_std: 0.01}
      ekf: {enabled: true, r_pos: 0.5, accel_noise_std: 0.2}
      lidar: {enabled: true, max_distance: 5.0, angle_resolution: 5.0}
    components:
      controller_x: {gains: {Kp: 0.8, Ki: 0.0, Kd: 0.1}, windup: 1.0}
      controller_y: {gains: {Kp: 0.8, Ki: 0.0, Kd: 0.1}, windup: 1.0}
      controller_z: {gains: {Kp: 2.0, Ki: 0.1, Kd: 1.0}, windup: 1.0}

  # SUIVEUR 1
  - type: "uav"
    name: "drone_1"
    urdf_path: "assets/quadrotor.urdf"
    start_pos: [-1.0, -1.0, 0.5]
    logging: {enabled: false}
    acc_limit_xy: 3.0
    sensors:
      gps: {enabled: true}
      imu: {enabled: true}
      ekf: {enabled: true}
      lidar: {enabled: false}
    components:
      controller_x: {gains: {Kp: 0.8, Kd: 0.1}}
      controller_y: {gains: {Kp: 0.8, Kd: 0.1}}
      controller_z: {gains: {Kp: 2.0, Kd: 1.0}}

  # SUIVEUR 2
  - type: "uav"
    name: "drone_2"
    urdf_path: "assets/quadrotor.urdf"
    start_pos: [-1.0, 1.0, 0.5]
    logging: {enabled: false}
    acc_limit_xy: 3.0
    sensors:
      gps: {enabled: true}
      imu: {enabled: true}
      ekf: {enabled: true}
      lidar: {enabled: false}
    components:
      controller_x: {gains: {Kp: 0.8, Kd: 0.1}}
      controller_y: {gains: {Kp: 0.8, Kd: 0.1}}
      controller_z: {gains: {Kp: 2.0, Kd: 1.0}}
