flowchart LR
  subgraph App
    main["main_py"]
    config["config_yaml"]
    sim["SimulationManager"]
  end

  subgraph Physics
    pyb["PyBullet"]
    world["World"]
  end

  subgraph SwarmLayer
    swarm["Swarm"]
  end

  subgraph Proxy
    proxy["Proxy"]
  end

  subgraph UAVLayer
    agent["Agent"]
    uav["UAV"]
    pid["PID"]
    sensors["Sensors"]
    ekf["EKF"]
    logger["Logger_CSV"]
  end

  subgraph SensorNodes
    gnss["GNSSSensor"]
    imu["IMUSensor"]
    lidar["LidarSensor"]
  end

  %% Application flow
  main -->|read_config| config
  main -->|create_simulation| sim

  %% Simulation and physics
  sim -->|init_physics| pyb
  sim -->|create_world| world
  sim -->|create_swarm| swarm

  %% Swarm creates UAVs
  swarm -->|create_uav| uav

  %% Message passing via Proxy
  swarm -->|send_commands| proxy
  proxy -->|forward_commands| uav


  %% Inheritance
  agent -->|base_class_of| uav

  %% UAV internal components
  uav --> pid
  uav --> sensors
  uav --> ekf
  uav --> logger

  %% Sensors inside UAV
  sensors --> gnss
  sensors --> imu
  sensors --> lidar

  %% Data flow
  pyb -->|ground_truth_state_to_control| uav

  gnss -->|gnss_measurements| uav
  gnss -->|gnss_measurements| ekf
  imu -->|imu_measurements| uav
  imu -->|imu_measurements| ekf
  lidar -->|lidar_measurements| uav

  ekf -->|estimated_state_to_uav| uav
  ekf -->|estimated_state_to_pid| pid

  uav -->|log_data| logger
