#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
causal_analysis.py

Advanced causal analysis for UxS (drone swarm) networks:
- Failure detection (collisions, formation loss, suboptimal trajectories, GNSS degradation, wind-related losses).
- Inter-drone interaction graph inference via Neural Relational Inference (NRI).
- Complementary causal scores (Granger) for exogenous factors (wind, GNSS).
- Probabilistic attribution of potential root causes per detected event.

This script is designed to work directly with the CSV logs generated by the project
(entities/uav.py : logs/drone_*.csv), while remaining generic.

References (implementation inspired by classic NRI architectures):
- Kipf et al., "Neural Relational Inference for Interacting Systems", ICML 2018.
- PyTorch NRI repo (Fetaya et al.): https://github.com/ethanfetaya/NRI
- Granger causality (statsmodels): https://www.statsmodels.org/

Outputs:
- Matrices (CSV/NPY): drone→drone influence, signed influences, systemic impacts.
- Figures (PNG): heatmaps, directed graphs, event probability time-series, cause attributions.

Quick usage (from project root):
    python analysis/causal_analysis.py --log_dir logs --output_dir causal_out

Adjust speed/quality:
    python analysis/causal_analysis.py --downsample 4 --nri_steps 1500 --seq_len 30

Notes:
- NRI here is "unsupervised" in the sense that it learns a latent graph by minimizing
  next-step prediction error on observed states.
- The "cause probabilities" are *hypotheses* (root-cause candidates), produced by a
  simple explanatory model (logistic regression) and aggregated by factor groups.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import warnings
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")  # safe for headless
import matplotlib.pyplot as plt

import networkx as nx

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from statsmodels.tsa.stattools import grangercausalitytests


# ---------------------------
# Utilities
# ---------------------------

def set_seed(seed: int) -> None:
    """Set RNG seeds for Python, NumPy, and PyTorch."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def set_torch_threads(n: int) -> None:
    """
    PyTorch can be *very* slow on tiny tensors when many CPU threads are enabled.
    Setting n=1 (or 2) is often 10x-1000x faster for this kind of NRI pipeline.
    """
    n = int(max(1, n))
    try:
        torch.set_num_threads(n)
    except Exception:
        pass
    try:
        torch.set_num_interop_threads(n)
    except Exception:
        pass


def ensure_dir(path: str) -> None:
    """Create a directory if it does not exist."""
    os.makedirs(path, exist_ok=True)


def to_numpy(x):
    """Detach Torch tensors to CPU NumPy arrays; pass-through otherwise."""
    if isinstance(x, torch.Tensor):
        return x.detach().cpu().numpy()
    return np.asarray(x)


def softmax_np(x: np.ndarray, axis: int = -1, eps: float = 1e-12) -> np.ndarray:
    """Numerically-stable softmax for NumPy arrays."""
    x = x - np.max(x, axis=axis, keepdims=True)
    ex = np.exp(x)
    return ex / (np.sum(ex, axis=axis, keepdims=True) + eps)


def robust_zscore(x: np.ndarray, eps: float = 1e-9) -> np.ndarray:
    """Robust z-score using median and MAD."""
    med = np.nanmedian(x)
    mad = np.nanmedian(np.abs(x - med)) + eps
    return 0.6745 * (x - med) / mad


# ---------------------------
# Data loading and features
# ---------------------------

@dataclass
class SwarmLogs:
    """Container for aligned swarm logs."""
    times: np.ndarray                 # [T]
    drone_names: List[str]            # [N]
    data: Dict[str, np.ndarray]       # key -> [T, N, dim] or [T, N]
    dt: float


def _find_drone_logs(log_dir: str) -> List[str]:
    """Return sorted paths matching drone_*.csv in the given directory."""
    paths = []
    for fn in os.listdir(log_dir):
        if fn.startswith("drone_") and fn.endswith(".csv"):
            paths.append(os.path.join(log_dir, fn))
    return sorted(paths)


def load_swarm_logs(log_dir: str, downsample: int = 1) -> SwarmLogs:
    """
    Load drone logs, align them by time, and return structured arrays.

    Expected columns (from entities/uav.py):
      time, gt_x,gt_y,gt_z, gt_vx,gt_vy,gt_vz, meas_x,meas_y,meas_z,
      gnss_error_mag, wind_x,wind_y,wind_z, wind_mag, rep_force_mag,
      nearest_neighbor_dist, target_x,target_y,target_z, tracking_error_mag, collision_flag
    """
    paths = _find_drone_logs(log_dir)
    if not paths:
        raise FileNotFoundError(
            f"No 'drone_*.csv' log files found in: {log_dir}"
        )

    dfs = []
    names = []
    for p in paths:
        df = pd.read_csv(p)
        # Basic checks and cleaning
        if "time" not in df.columns:
            raise ValueError(f"Missing 'time' column in {p}. Columns: {list(df.columns)}")
        df = df.copy()
        df.sort_values("time", inplace=True)
        if downsample > 1:
            df = df.iloc[::downsample].reset_index(drop=True)
        df.ffill(inplace=True)
        df.bfill(inplace=True)
        dfs.append(df)
        names.append(os.path.splitext(os.path.basename(p))[0])

    # Align by time (inner join on rounded time)
    # Times are already rounded to 0.001 in logs, but we align robustly anyway.
    base = dfs[0][["time"]].copy()
    base["time"] = base["time"].round(3)

    aligned = [base]
    for df in dfs:
        tmp = df.copy()
        tmp["time"] = tmp["time"].round(3)
        aligned.append(tmp)

    # Keep the intersection of times across all drones
    common_times = aligned[1]["time"].to_numpy()
    for k in range(2, len(aligned)):
        common_times = np.intersect1d(common_times, aligned[k]["time"].to_numpy())

    if len(common_times) < 10:
        raise ValueError(
            "Too few common timestamps across drones. "
            "Make sure the logs come from the same simulation/run."
        )

    # Reindex each dataframe on common times
    dfs2 = []
    for df in dfs:
        tmp = df.copy()
        tmp["time"] = tmp["time"].round(3)
        tmp = tmp.set_index("time").loc[common_times].reset_index()
        tmp.ffill(inplace=True)
        tmp.bfill(inplace=True)
        dfs2.append(tmp)

    times = dfs2[0]["time"].values.astype(np.float32)
    if len(times) >= 2:
        dt = float(np.median(np.diff(times)))
    else:
        dt = 0.1

    # Stack fields
    def stack_cols(cols: List[str]) -> np.ndarray:
        """Stack multiple columns into [T, N, len(cols)]."""
        arrs = []
        for df in dfs2:
            arr = df[cols].values.astype(np.float32)
            arrs.append(arr)
        return np.stack(arrs, axis=1)  # [T, N, len(cols)]

    def stack_col(col: str) -> np.ndarray:
        """Stack a single column into [T, N]."""
        arrs = []
        for df in dfs2:
            arr = df[col].values.astype(np.float32)
            arrs.append(arr)
        return np.stack(arrs, axis=1)  # [T, N]

    data: Dict[str, np.ndarray] = {}
    data["gt_pos"] = stack_cols(["gt_x", "gt_y", "gt_z"])
    data["gt_vel"] = stack_cols(["gt_vx", "gt_vy", "gt_vz"])
    data["meas_pos"] = stack_cols(["meas_x", "meas_y", "meas_z"])
    data["wind"] = stack_cols(["wind_x", "wind_y", "wind_z"])
    data["wind_mag"] = stack_col("wind_mag")
    data["gnss_error_mag"] = stack_col("gnss_error_mag")
    data["rep_force_mag"] = stack_col("rep_force_mag")
    data["nearest_neighbor_dist"] = stack_col("nearest_neighbor_dist")
    data["target_pos"] = stack_cols(["target_x", "target_y", "target_z"])
    data["tracking_error_mag"] = stack_col("tracking_error_mag")
    data["collision_flag_log"] = stack_col("collision_flag")  # from pybullet contact points

    return SwarmLogs(times=times, drone_names=names, data=data, dt=dt)


# ---------------------------
# Failure detection (labels)
# ---------------------------

@dataclass
class FailureLabels:
    """Binary labels per event type + auxiliary signals."""
    # Each is [T, N] (binary)
    collision: np.ndarray
    formation_loss: np.ndarray
    gnss_degradation: np.ndarray
    wind_loss: np.ndarray
    suboptimal_traj: np.ndarray

    # Auxiliary signals
    formation_error: np.ndarray      # [T, N]
    min_pairwise_dist: np.ndarray    # [T, N]
    speed: np.ndarray                # [T, N]


def compute_pairwise_dists(pos: np.ndarray) -> np.ndarray:
    """Compute pairwise distances: pos [T,N,3] -> dists [T,N,N]."""
    T, N, _ = pos.shape
    d = pos[:, :, None, :] - pos[:, None, :, :]
    d2 = np.sum(d * d, axis=-1)
    dist = np.sqrt(np.maximum(d2, 0.0))
    return dist


def compute_proximity_fraction(pos: np.ndarray, radius: float) -> np.ndarray:
    """
    Fraction of time each pair (i,j) is within `radius` (i receives from j).

    Returns:
        frac: [N, N] in [0,1], diag=0
    """
    dists = compute_pairwise_dists(pos)  # [T,N,N]
    T, N, _ = dists.shape
    for t in range(T):
        np.fill_diagonal(dists[t], np.inf)
    close = (dists < float(radius))
    frac = close.mean(axis=0).astype(np.float32)
    np.fill_diagonal(frac, 0.0)
    return frac


def _parse_indices(spec: str, n: int) -> List[int]:
    """Parse a comma-separated list of indices; keep only unique valid indices in [0, n-1]."""
    if spec is None:
        return []
    spec = str(spec).strip()
    if not spec:
        return []
    out = []
    for part in spec.split(','):
        part = part.strip()
        if not part:
            continue
        try:
            idx = int(part)
        except ValueError:
            continue
        if 0 <= idx < n and idx not in out:
            out.append(idx)
    return out


def _apply_persistence(x: np.ndarray, min_steps: int) -> np.ndarray:
    """Enforce `min_steps` consecutive 1s on a binary array x: [T,N]."""
    if min_steps <= 1:
        return x.astype(np.int32)
    T, N = x.shape
    y = np.zeros_like(x, dtype=np.int32)
    for i in range(N):
        run = 0
        for t in range(T):
            if x[t, i] == 1:
                run += 1
            else:
                run = 0
            if run >= min_steps:
                y[t, i] = 1
    return y


def detect_failures(
    logs: SwarmLogs,
    leader_index: int = 0,
    collision_dist: float = 0.6,
    formation_thresh: float = 1.0,
    gnss_quantile: float = 0.95,
    wind_quantile: float = 0.95,
    suboptimal_quantile: float = 0.95,
    suboptimal_persist_steps: int = 5,
    event_persist_steps: int = 5,
    swarm_indices: Optional[List[int]] = None,
    independent_indices: Optional[List[int]] = None,
    target_jump_thresh: float = 20.0,
    smooth_window: int = 5,
) -> FailureLabels:
    """
    Mission-aware detection heuristics:

    - collision: min inter-drone distance < collision_dist

    - formation_loss: computed *only* for the swarm (swarm_indices).
      We measure "shape deformation" via intra-swarm inter-drone distances
      (translation/rotation invariant). For drones outside the swarm (e.g., drone_3),
      formation_error = 0 and formation_loss = 0.

    - gnss_degradation: global threshold (quantile over all values) + persistence

    - wind_loss: global wind_mag threshold + positive slope of smoothed tracking_error + persistence

    - suboptimal_traj: smoothed tracking_error > global threshold + persistence,
      while ignoring "target jumps" (waypoint artifacts).
    """
    pos = logs.data["gt_pos"]  # [T,N,3]
    vel = logs.data["gt_vel"]
    wind_mag = logs.data["wind_mag"]
    gnss_err = logs.data["gnss_error_mag"]
    track_err = logs.data["tracking_error_mag"]
    target_pos = logs.data.get("target_pos", None)

    T, N, _ = pos.shape

    if swarm_indices is None:
        # Default explicit swarm {0,1,2} if possible
        swarm_indices = [i for i in [0, 1, 2] if i < N]
    if independent_indices is None:
        independent_indices = [3] if N > 3 else []
    # Keep only valid unique indices
    swarm_indices = [i for i in swarm_indices if 0 <= i < N]
    independent_indices = [i for i in independent_indices if 0 <= i < N]

    # Pairwise distances
    dists = compute_pairwise_dists(pos)  # [T,N,N]
    for t in range(T):
        np.fill_diagonal(dists[t], np.inf)
    min_dist = np.min(dists, axis=-1)  # [T,N]

    collision = (min_dist < collision_dist).astype(np.int32)

    # --- Formation error: only within swarm ---
    formation_error = np.zeros((T, N), dtype=np.float32)
    formation_loss = np.zeros((T, N), dtype=np.int32)
    if len(swarm_indices) >= 2:
        d0 = dists[0]  # [N,N]
        # For each swarm drone i, average absolute deviation of distances to other swarm drones
        for i in swarm_indices:
            js = [j for j in swarm_indices if j != i]
            if not js:
                continue
            diff = np.abs(dists[:, i, js] - d0[i, js][None, :])  # [T,|js|]
            formation_error[:, i] = np.mean(diff, axis=-1)
        formation_loss[:, swarm_indices] = (formation_error[:, swarm_indices] > formation_thresh).astype(np.int32)

    # --- GNSS degradation: GLOBAL threshold + persistence ---
    gnss_thr = float(np.quantile(gnss_err.reshape(-1), gnss_quantile))
    gnss_degradation = (gnss_err > gnss_thr).astype(np.int32)
    gnss_degradation = _apply_persistence(gnss_degradation, event_persist_steps)

    # --- Smooth tracking error ---
    track_smooth = track_err.copy().astype(np.float32)
    if smooth_window and smooth_window > 1:
        # Simple rolling median per drone
        w = int(smooth_window)
        pad = w // 2
        for i in range(N):
            x = track_err[:, i]
            xp = np.pad(x, (pad, pad), mode='edge')
            med = np.zeros_like(x)
            for t in range(T):
                med[t] = np.median(xp[t:t+w])
            track_smooth[:, i] = med

    # --- Wind loss: GLOBAL wind threshold + positive slope of smoothed tracking error + persistence ---
    wind_thr = float(np.quantile(wind_mag.reshape(-1), wind_quantile))
    d_track = np.zeros_like(track_smooth)
    d_track[1:] = (track_smooth[1:] - track_smooth[:-1]) / max(logs.dt, 1e-6)
    wind_loss = ((wind_mag > wind_thr) & (d_track > 0.5)).astype(np.int32)
    wind_loss = _apply_persistence(wind_loss, event_persist_steps)

    # --- Suboptimal trajectory: GLOBAL threshold + persistence, ignore target jumps ---
    jump_mask = np.zeros((T, N), dtype=bool)
    if target_pos is not None:
        # Mark timesteps where target jumps too far in one step
        dtar = np.zeros((T, N), dtype=np.float32)
        dtar[1:] = np.linalg.norm(target_pos[1:] - target_pos[:-1], axis=-1)
        jump_mask = dtar > float(target_jump_thresh)

    # Compute threshold excluding jump timesteps (flatten)
    valid_vals = track_smooth[~jump_mask]
    if valid_vals.size < 10:
        sub_thr = float(np.quantile(track_smooth.reshape(-1), suboptimal_quantile))
    else:
        sub_thr = float(np.quantile(valid_vals, suboptimal_quantile))

    suboptimal = (track_smooth > sub_thr).astype(np.int32)
    suboptimal[jump_mask] = 0
    suboptimal = _apply_persistence(suboptimal, suboptimal_persist_steps)

    speed = np.linalg.norm(vel, axis=-1)  # [T,N]

    return FailureLabels(
        collision=collision,
        formation_loss=formation_loss,
        gnss_degradation=gnss_degradation,
        wind_loss=wind_loss,
        suboptimal_traj=suboptimal,
        formation_error=formation_error.astype(np.float32),
        min_pairwise_dist=min_dist.astype(np.float32),
        speed=speed.astype(np.float32),
    )


# ---------------------------
# NRI model (PyTorch)
# ---------------------------

class MLP(nn.Module):
    """Simple 2-layer MLP with optional dropout."""
    def __init__(self, in_dim: int, hidden_dim: int, out_dim: int, dropout: float = 0.0):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, out_dim)
        self.dropout = dropout

    def forward(self, x):
        x = F.relu(self.fc1(x))
        if self.dropout > 0:
            x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.fc2(x)
        return x


def gumbel_softmax_sample(logits, tau=1.0, eps=1e-10):
    """Sample from the Gumbel-Softmax distribution."""
    U = torch.rand_like(logits)
    g = -torch.log(-torch.log(U + eps) + eps)
    y = logits + g
    return F.softmax(y / tau, dim=-1)


def gumbel_softmax(logits, tau=1.0, hard=False):
    """
    Gumbel-Softmax with optional straight-through hard sampling.
    Returns a differentiable approximation of one-hot edge types.
    """
    y = gumbel_softmax_sample(logits, tau=tau)
    if not hard:
        return y
    # Straight-through estimator
    shape = y.size()
    _, ind = y.max(dim=-1)
    y_hard = torch.zeros_like(y).view(-1, shape[-1])
    y_hard.scatter_(1, ind.view(-1, 1), 1)
    y_hard = y_hard.view(*shape)
    y = (y_hard - y).detach() + y
    return y


def build_offdiag_indices(n: int, device: torch.device) -> Tuple[torch.Tensor, torch.Tensor]:
    """Return sender/receiver indices for all directed edges excluding self edges."""
    offdiag = np.ones((n, n)) - np.eye(n)
    receivers, senders = np.where(offdiag)
    receivers = torch.tensor(receivers, dtype=torch.long, device=device)
    senders = torch.tensor(senders, dtype=torch.long, device=device)
    return senders, receivers  # each is [E]


class NRIEncoder(nn.Module):
    """
    Classic NRI-style encoder: encode node features, then infer edge-type logits.

    Input:
        x_flat: [B, N, D_in]  (time-aggregated window features)
    Output:
        logits: [B, E, K]
    """
    def __init__(self, n_nodes: int, d_in: int, hidden: int, n_edge_types: int, dropout: float = 0.0):
        super().__init__()
        self.n_nodes = n_nodes
        self.d_in = d_in
        self.hidden = hidden
        self.n_edge_types = n_edge_types
        # Node embedding
        self.node_mlp = MLP(in_dim=d_in, hidden_dim=hidden, out_dim=hidden, dropout=dropout)
        # Edge MLP from concatenated sender/receiver embeddings and their difference
        self.edge_mlp = MLP(in_dim=3 * hidden, hidden_dim=hidden, out_dim=n_edge_types, dropout=dropout)

    def forward(self, x_flat: torch.Tensor, senders: torch.Tensor, receivers: torch.Tensor):
        """
        Args:
            x_flat: [B, N, D_in]
        Returns:
            logits: [B, E, K]
        """
        B, N, D = x_flat.shape
        assert N == self.n_nodes

        h = self.node_mlp(x_flat)  # [B,N,H]
        h_send = h[:, senders, :]  # [B,E,H]
        h_recv = h[:, receivers, :]
        h_diff = h_send - h_recv
        edge_in = torch.cat([h_send, h_recv, h_diff], dim=-1)  # [B,E,3H]
        logits = self.edge_mlp(edge_in)  # [B,E,K]
        return logits


class NRIDecoder(nn.Module):
    """
    Message passing decoder for next-step prediction.

    Given current state s_t, exogenous u_t, and edges z_ij (soft one-hot over K),
    predict a residual delta to produce s_{t+1}.
    """
    def __init__(self, n_nodes: int, state_dim: int, exog_dim: int, hidden: int, n_edge_types: int, dropout: float = 0.0):
        super().__init__()
        self.n_nodes = n_nodes
        self.state_dim = state_dim
        self.exog_dim = exog_dim
        self.hidden = hidden
        self.n_edge_types = n_edge_types

        # Per-edge-type message networks
        self.msg_mlps = nn.ModuleList([
            MLP(in_dim=2 * state_dim, hidden_dim=hidden, out_dim=hidden, dropout=dropout)
            for _ in range(n_edge_types)
        ])
        # Node update network
        self.node_mlp = MLP(in_dim=state_dim + exog_dim + hidden, hidden_dim=hidden, out_dim=state_dim, dropout=dropout)

    def forward(self, s: torch.Tensor, u: torch.Tensor, z: torch.Tensor,
                senders: torch.Tensor, receivers: torch.Tensor) -> torch.Tensor:
        """
        Args:
            s: [B, N, S]
            u: [B, N, U]
            z: [B, E, K] soft edge types
        Returns:
            s_next_pred: [B, N, S]
        """
        B, N, S = s.shape
        E = senders.shape[0]

        s_send = s[:, senders, :]  # [B,E,S]
        s_recv = s[:, receivers, :]  # [B,E,S]
        edge_feat = torch.cat([s_send, s_recv], dim=-1)  # [B,E,2S]

        # Compute messages per edge type, weighted by z
        msg_all = 0.0
        for k in range(self.n_edge_types):
            msg_k = self.msg_mlps[k](edge_feat)  # [B,E,H]
            w = z[..., k:k + 1]  # [B,E,1]
            msg_all = msg_all + w * msg_k

        # Aggregate incoming messages per receiver
        agg = torch.zeros((B, N, self.hidden), device=s.device, dtype=s.dtype)  # [B,N,H]
        agg.index_add_(1, receivers, msg_all)  # sum over incoming edges

        node_in = torch.cat([s, u, agg], dim=-1)  # [B,N,S+U+H]
        delta = self.node_mlp(node_in)  # [B,N,S]
        s_next = s + delta
        return s_next


class NRIModel(nn.Module):
    """Encoder-decoder NRI model for latent graph inference and dynamics prediction."""
    def __init__(self, n_nodes: int, state_dim: int, exog_dim: int,
                 hidden: int = 128, n_edge_types: int = 3, dropout: float = 0.0):
        super().__init__()
        self.n_nodes = n_nodes
        self.state_dim = state_dim
        self.exog_dim = exog_dim
        self.hidden = hidden
        self.n_edge_types = n_edge_types

        # Encoder takes time-aggregated node features; we pass mean over a window
        self.encoder = NRIEncoder(n_nodes=n_nodes, d_in=state_dim, hidden=hidden, n_edge_types=n_edge_types, dropout=dropout)
        self.decoder = NRIDecoder(n_nodes=n_nodes, state_dim=state_dim, exog_dim=exog_dim, hidden=hidden, n_edge_types=n_edge_types, dropout=dropout)

    def infer_edges(self, s_window: torch.Tensor, senders: torch.Tensor, receivers: torch.Tensor,
                    tau: float = 0.5, hard: bool = False) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            s_window: [B, L, N, S]
        Returns:
            z: [B, E, K] soft/hard edge types
            logits: [B, E, K]
        """
        s_mean = torch.mean(s_window, dim=1)  # [B,N,S]
        logits = self.encoder(s_mean, senders, receivers)
        z = gumbel_softmax(logits, tau=tau, hard=hard)
        return z, logits

    def forward(self, s_window: torch.Tensor, u_window: torch.Tensor,
                senders: torch.Tensor, receivers: torch.Tensor,
                tau: float = 0.5, hard: bool = False) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Predict next steps within a window using teacher forcing.

        Args:
            s_window: [B, L, N, S]
            u_window: [B, L, N, U]
        Returns:
            s_pred: [B, L-1, N, S]
            z: [B, E, K]
            logits: [B, E, K]
        """
        z, logits = self.infer_edges(s_window, senders, receivers, tau=tau, hard=hard)
        B, L, N, S = s_window.shape
        preds = []
        s_t = s_window[:, 0, :, :]
        for t in range(L - 1):
            u_t = u_window[:, t, :, :]
            s_next = self.decoder(s_t, u_t, z, senders, receivers)
            preds.append(s_next)
            s_t = s_window[:, t + 1, :, :]  # teacher forcing
        s_pred = torch.stack(preds, dim=1)  # [B,L-1,N,S]
        return s_pred, z, logits


# ---------------------------
# Preparing sequences
# ---------------------------

@dataclass
class SequenceDataset:
    """State/exogenous sequences used by NRI."""
    s: np.ndarray      # [T,N,S]
    u: np.ndarray      # [T,N,U]
    times: np.ndarray  # [T]

    def sample_windows(self, seq_len: int, n_samples: int, rng: np.random.RandomState) -> Tuple[np.ndarray, np.ndarray]:
        """
        Sample random windows.

        Returns:
            s_win: [B, L, N, S]
            u_win: [B, L, N, U]
        """
        T = self.s.shape[0]
        if T <= seq_len + 1:
            raise ValueError(f"Not enough timesteps T={T} for seq_len={seq_len}")

        starts = rng.randint(0, T - seq_len, size=n_samples)
        s_w = np.stack([self.s[i:i + seq_len] for i in starts], axis=0)
        u_w = np.stack([self.u[i:i + seq_len] for i in starts], axis=0)
        return s_w, u_w


def build_sequence_dataset(logs: SwarmLogs, use_measured: bool = False) -> SequenceDataset:
    """
    Build the dataset consumed by NRI.

    - s: state = [pos, vel]. By default uses ground truth.
    - u: exogenous per drone = [wind_vector(3), gnss_error_mag(1)].
    """
    if use_measured:
        pos = logs.data["meas_pos"]
        # Approximate velocity via finite differences
        vel = np.zeros_like(pos)
        vel[1:] = (pos[1:] - pos[:-1]) / max(logs.dt, 1e-6)
    else:
        pos = logs.data["gt_pos"]
        vel = logs.data["gt_vel"]

    s = np.concatenate([pos, vel], axis=-1)  # [T,N,6]
    wind = logs.data["wind"]  # [T,N,3]
    gnss = logs.data["gnss_error_mag"][..., None]  # [T,N,1]
    u = np.concatenate([wind, gnss], axis=-1)  # [T,N,4]
    return SequenceDataset(s=s.astype(np.float32), u=u.astype(np.float32), times=logs.times.astype(np.float32))


# ---------------------------
# Train NRI
# ---------------------------

@dataclass
class NRIResults:
    """Outputs of NRI training/inference."""
    edge_probs: np.ndarray       # [N,N] probability of "some interaction" (1 - p(no-edge))
    edge_type_probs: np.ndarray  # [K,N,N] probability of each edge type
    signed_influence: np.ndarray # [N,N] signed influence (heuristic sign * edge_probs)
    nri_loss_curve: List[float]


def train_nri(
    dataset: SequenceDataset,
    n_nodes: int,
    seq_len: int = 30,
    n_edge_types: int = 3,
    hidden: int = 128,
    dropout: float = 0.0,
    batch_size: int = 64,
    nri_steps: int = 2000,
    lr: float = 3e-4,
    tau_start: float = 1.0,
    tau_end: float = 0.5,
    tau_anneal_steps: int = 1500,
    max_train_windows: int = 5000,
    device: str = "cpu",
    torch_threads: int = 1,
    seed: int = 0,
    verbose_every: int = 100,
) -> NRIResults:
    """Train NRI with one-step prediction and return inferred edge probabilities."""
    set_seed(seed)
    dev = torch.device(device)
    set_torch_threads(torch_threads)

    S = dataset.s.shape[-1]
    U = dataset.u.shape[-1]

    model = NRIModel(n_nodes=n_nodes, state_dim=S, exog_dim=U, hidden=hidden,
                     n_edge_types=n_edge_types, dropout=dropout).to(dev)
    opt = torch.optim.Adam(model.parameters(), lr=lr)

    senders, receivers = build_offdiag_indices(n_nodes, dev)

    # Standardize s and u (important for stable training)
    s_flat = dataset.s.reshape(-1, S)
    u_flat = dataset.u.reshape(-1, U)
    s_scaler = StandardScaler().fit(s_flat)
    u_scaler = StandardScaler().fit(u_flat)

    s_std = s_scaler.transform(s_flat).reshape(dataset.s.shape).astype(np.float32)
    u_std = u_scaler.transform(u_flat).reshape(dataset.u.shape).astype(np.float32)
    ds_std = SequenceDataset(s=s_std, u=u_std, times=dataset.times)

    rng = np.random.RandomState(seed)
    loss_curve: List[float] = []

    # Window pool ("reservoir") for faster training
    n_windows = min(max_train_windows, max(1000, batch_size * 10))
    # For speed: one-step prediction using a context of length seq_len and predicting the next transition
    s_w_all, u_w_all = ds_std.sample_windows(seq_len=seq_len + 1, n_samples=n_windows, rng=rng)

    s_w_all_t = torch.from_numpy(s_w_all).to(dev)
    u_w_all_t = torch.from_numpy(u_w_all).to(dev)

    model.train()
    for step in range(1, nri_steps + 1):
        # Anneal tau
        if step <= tau_anneal_steps:
            tau = tau_start + (tau_end - tau_start) * (step / tau_anneal_steps)
        else:
            tau = tau_end

        idx = rng.randint(0, n_windows, size=batch_size)
        s_win = s_w_all_t[idx]  # [B,L+1,N,S]
        u_win = u_w_all_t[idx]

        # Context for inferring the latent graph
        s_ctx = s_win[:, :seq_len, :, :]   # [B,L,N,S]
        # Transition inputs at time t = seq_len-1 -> seq_len
        s_t = s_win[:, seq_len - 1, :, :]  # [B,N,S]
        u_t = u_win[:, seq_len - 1, :, :]  # [B,N,U]
        target = s_win[:, seq_len, :, :]   # [B,N,S]

        z, logits = model.infer_edges(s_ctx, senders, receivers, tau=tau, hard=False)
        s_pred = model.decoder(s_t, u_t, z, senders, receivers)

        loss = F.mse_loss(s_pred, target)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        loss_curve.append(float(loss.item()))
        if verbose_every and (step % verbose_every == 0 or step == 1):
            print(f"[NRI] step={step:5d}/{nri_steps}  tau={tau:.3f}  mse={loss.item():.6f}")

    # Infer edge probabilities by running encoder over many windows and averaging z
    model.eval()
    with torch.no_grad():
        B_eval = min(1024, n_windows)
        idx = rng.choice(n_windows, size=B_eval, replace=False)
        s_win = s_w_all_t[idx][:, :seq_len, :, :]
        z, logits = model.infer_edges(s_win, senders, receivers, tau=tau_end, hard=False)  # [B,E,K]
        z_mean = torch.mean(z, dim=0)  # [E,K]
        z_mean = to_numpy(z_mean)  # [E,K]

    # Build adjacency matrices
    N = n_nodes
    K = n_edge_types
    edge_type_probs = np.zeros((K, N, N), dtype=np.float32)
    edge_probs = np.zeros((N, N), dtype=np.float32)

    E = len(senders)
    send_np = to_numpy(senders).astype(int)
    recv_np = to_numpy(receivers).astype(int)
    for e in range(E):
        j = send_np[e]
        i = recv_np[e]
        for k in range(K):
            edge_type_probs[k, i, j] = float(z_mean[e, k])
        # Interaction probability = 1 - p(no-edge); assume type 0 = no-edge by convention
        edge_probs[i, j] = float(1.0 - z_mean[e, 0])

    # Signed influence heuristic from data
    signed = estimate_signed_influence(dataset.s, edge_probs, leader_index=0)

    return NRIResults(
        edge_probs=edge_probs,
        edge_type_probs=edge_type_probs,
        signed_influence=signed,
        nri_loss_curve=loss_curve,
    )


def estimate_signed_influence(states: np.ndarray, edge_probs: np.ndarray, leader_index: int = 0) -> np.ndarray:
    """
    Heuristic for "sign" (repulsive / attractive) based on dynamics:

    - states: [T,N,6] = pos(3) + vel(3)
    - approximate a_i ~ dv_i and compute mean sign of dot(a_i, (p_i - p_j)) / ||p_i - p_j||^2
        > 0: accelerates away from j (repulsive)
        < 0: accelerates toward j (attractive)

    The returned matrix is sign * edge_prob.
    """
    pos = states[..., :3]
    vel = states[..., 3:6]
    T, N, _ = pos.shape

    # Finite-difference acceleration (dt scale not needed for sign)
    acc = np.zeros_like(vel)
    acc[1:] = vel[1:] - vel[:-1]

    signed = np.zeros((N, N), dtype=np.float32)
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            rel = pos[:, i, :] - pos[:, j, :]  # [T,3]
            dot = np.sum(acc[:, i, :] * rel, axis=-1)  # [T]
            denom = np.sum(rel * rel, axis=-1) + 1e-6
            score = np.nanmean(dot / denom)
            sign = 1.0 if score > 0 else -1.0
            signed[i, j] = sign * float(edge_probs[i, j])
    return signed


# ---------------------------
# Exogenous causal scores (Granger) + Event models
# ---------------------------

@dataclass
class GrangerResults:
    """
    Granger evidence results.

    - scores[event][factor] -> [N] scores in [0,1] (1 = strong evidence that factor Granger-causes event)
    - min_pvalues[event][factor] -> [N] minimum p-value across tested lags
    """
    scores: Dict[str, Dict[str, np.ndarray]]
    min_pvalues: Dict[str, Dict[str, np.ndarray]]


def safe_granger_score(x: np.ndarray, y: np.ndarray, maxlag: int = 5) -> Tuple[float, float]:
    """
    Granger test y ~ past(y,x): does x help predict y?

    Returns:
        (score, min_pvalue)
        score is mapped as 1 - min_pvalue (clipped to [0,1]).
    """
    try:
        # statsmodels expects data [T,2] with columns [y, x] when testing "x causes y"
        data = np.column_stack([y, x]).astype(np.float64)
        # Silence statsmodels output
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = grangercausalitytests(data, maxlag=maxlag, verbose=False)
        pvals = []
        for lag, out in res.items():
            pvals.append(out[0]["ssr_ftest"][1])  # F-test p-value
        min_p = float(np.min(pvals))
        score = float(np.clip(1.0 - min_p, 0.0, 1.0))
        return score, min_p
    except Exception:
        return 0.0, 1.0


def compute_granger(logs: SwarmLogs, labels: FailureLabels, maxlag: int = 5) -> GrangerResults:
    """Compute Granger-style evidence that wind/GNSS predict events."""
    wind = logs.data["wind_mag"]  # [T,N]
    gnss = logs.data["gnss_error_mag"]
    events = {
        "collision": labels.collision,
        "formation_loss": labels.formation_loss,
        "gnss_degradation": labels.gnss_degradation,
        "wind_loss": labels.wind_loss,
        "suboptimal_traj": labels.suboptimal_traj,
    }
    factors = {
        "wind_mag": wind,
        "gnss_error_mag": gnss,
    }

    scores: Dict[str, Dict[str, np.ndarray]] = {}
    min_pvals: Dict[str, Dict[str, np.ndarray]] = {}
    for ev_name, ev in events.items():
        scores[ev_name] = {}
        min_pvals[ev_name] = {}
        for fac_name, fac in factors.items():
            N = ev.shape[1]
            sc = np.zeros(N, dtype=np.float32)
            pv = np.ones(N, dtype=np.float32)
            for i in range(N):
                s, p = safe_granger_score(fac[:, i], ev[:, i], maxlag=maxlag)
                sc[i] = s
                pv[i] = p
            scores[ev_name][fac_name] = sc
            min_pvals[ev_name][fac_name] = pv
    return GrangerResults(scores=scores, min_pvalues=min_pvals)


@dataclass
class EventModelOutputs:
    """Outputs of event prediction and root-cause attribution."""
    proba: Dict[str, np.ndarray]          # predicted probabilities per event type [T,N]
    event_causes: List[Dict]             # per-event instance explanations
    avg_causes: Dict[str, Dict[str, List[float]]]  # average cause probs per event and per drone


def build_interaction_pressure(pos: np.ndarray, edge_probs: np.ndarray, eps: float = 1e-3) -> np.ndarray:
    """
    Scalar feature per drone representing "pressure" from neighbors weighted by inferred edges.

    pressure_i = sum_j edge_prob[i<-j] / (dist_ij + eps)
    """
    dists = compute_pairwise_dists(pos)  # [T,N,N]
    T, N, _ = dists.shape
    for t in range(T):
        np.fill_diagonal(dists[t], np.inf)
    inv = 1.0 / (dists + eps)
    w = edge_probs[None, :, :]  # [1,N,N] receiver i, sender j
    pressure = np.sum(w * inv, axis=-1)  # [T,N]
    return pressure.astype(np.float32)


def fit_event_models(
    logs: SwarmLogs,
    labels: FailureLabels,
    edge_probs: np.ndarray,
    horizon_lag: int = 1,
    max_events_to_explain: int = 2000,
    seed: int = 0,
) -> EventModelOutputs:
    """
    Fit per-event logistic regression models to predict event(t) from features(t-lag).
    Convert coefficient contributions into per-event root-cause probability distributions.
    """
    rng = np.random.RandomState(seed)

    pos = logs.data["gt_pos"]
    wind = logs.data["wind_mag"]
    gnss = logs.data["gnss_error_mag"]
    repf = logs.data["rep_force_mag"]
    track = logs.data["tracking_error_mag"]
    formerr = labels.formation_error
    mindist = labels.min_pairwise_dist

    interaction_pressure = build_interaction_pressure(pos, edge_probs)  # [T,N]

    events = {
        "collision": labels.collision,
        "formation_loss": labels.formation_loss,
        "gnss_degradation": labels.gnss_degradation,
        "wind_loss": labels.wind_loss,
        "suboptimal_traj": labels.suboptimal_traj,
    }

    # Features at t-lag
    T, N = wind.shape
    lag = horizon_lag
    idx_t = np.arange(lag, T)  # drop first `lag` timesteps

    # Base feature matrix per (t,i)
    # Order matters for grouping later
    feature_names = [
        "wind_mag",
        "gnss_error_mag",
        "rep_force_mag",
        "tracking_error_mag",
        "formation_error",
        "min_pairwise_dist",
        "interaction_pressure",
    ]

    X = np.stack([
        wind[idx_t],
        gnss[idx_t],
        repf[idx_t],
        track[idx_t],
        formerr[idx_t],
        mindist[idx_t],
        interaction_pressure[idx_t],
    ], axis=-1)  # [T-lag, N, F]

    # Lagged features (t-lag)
    X_lag = np.stack([
        wind[idx_t - lag],
        gnss[idx_t - lag],
        repf[idx_t - lag],
        track[idx_t - lag],
        formerr[idx_t - lag],
        mindist[idx_t - lag],
        interaction_pressure[idx_t - lag],
    ], axis=-1)

    # Flatten
    Xf = X_lag.reshape(-1, X_lag.shape[-1])  # [(T-lag)*N, F]
    scaler = StandardScaler().fit(Xf)
    Xfs = scaler.transform(Xf)

    outputs_proba: Dict[str, np.ndarray] = {}
    event_causes: List[Dict] = []
    avg_causes: Dict[str, Dict[str, List[float]]] = {}

    # Factor grouping for root-cause attribution
    groups = {
        "wind": ["wind_mag"],
        "gnss": ["gnss_error_mag"],
        "interaction": ["rep_force_mag", "min_pairwise_dist", "interaction_pressure"],
        "formation_tracking": ["tracking_error_mag", "formation_error"],
    }
    name_to_idx = {n: k for k, n in enumerate(feature_names)}

    for ev_name, Y in events.items():
        y = Y[idx_t].reshape(-1).astype(int)  # [(T-lag)*N]
        # If extremely rare, skip
        if y.sum() < 10:
            print(f"[EventModel] '{ev_name}' too rare ({y.sum()} positives). Skipping model.")
            outputs_proba[ev_name] = np.zeros((T, N), dtype=np.float32)
            continue

        clf = LogisticRegression(max_iter=2000, class_weight="balanced", solver="lbfgs")
        clf.fit(Xfs, y)

        # Predict probabilities for all times (aligned)
        proba_all = np.zeros((T, N), dtype=np.float32)
        proba = clf.predict_proba(Xfs)[:, 1].reshape(len(idx_t), N)
        proba_all[idx_t] = proba.astype(np.float32)
        outputs_proba[ev_name] = proba_all

        # Root-cause explanations for positive instances
        coef = clf.coef_.reshape(-1)  # [F]
        # Contribution = coef_k * x_k (standardized space)
        contrib = Xfs * coef[None, :]  # [M,F]
        contrib = np.maximum(contrib, 0.0)  # keep only positive evidence

        pos_indices = np.where(y == 1)[0]
        if len(pos_indices) > max_events_to_explain:
            pos_indices = rng.choice(pos_indices, size=max_events_to_explain, replace=False)

        # Aggregate average cause by drone
        avg_causes[ev_name] = {g: [0.0] * N for g in groups.keys()}
        cnt_by_drone = np.zeros(N, dtype=int)

        for idx_flat in pos_indices:
            t_rel = idx_flat // N
            i = idx_flat % N
            t = int(idx_t[t_rel])  # absolute time index

            # Group scores
            g_scores = {}
            for g, names in groups.items():
                s = 0.0
                for nm in names:
                    s += float(contrib[idx_flat, name_to_idx[nm]])
                g_scores[g] = s

            # Softmax to probabilities
            vec = np.array(list(g_scores.values()), dtype=np.float32)
            probs = softmax_np(vec, axis=0)
            g_probs = {g: float(probs[k]) for k, g in enumerate(g_scores.keys())}

            event_causes.append({
                "event": ev_name,
                "time": float(logs.times[t]),
                "t_index": int(t),
                "drone": int(i),
                "drone_name": logs.drone_names[i],
                "predicted_event_probability": float(proba_all[t, i]),
                "cause_probabilities": g_probs,
                "raw_group_scores": g_scores,
            })

            # Accumulate averages
            cnt_by_drone[i] += 1
            for g in groups.keys():
                avg_causes[ev_name][g][i] += g_probs[g]

        for i in range(N):
            if cnt_by_drone[i] > 0:
                for g in groups.keys():
                    avg_causes[ev_name][g][i] /= float(cnt_by_drone[i])

        print(f"[EventModel] '{ev_name}': trained. Explained events: {len(pos_indices)}.")

    return EventModelOutputs(proba=outputs_proba, event_causes=event_causes, avg_causes=avg_causes)


# ---------------------------
# Systemic impact across the network
# ---------------------------

def compute_systemic_impact(events: np.ndarray, target_errors: np.ndarray, horizon_steps: int = 10) -> np.ndarray:
    """
    Estimate systemic impacts across the swarm.

    Args:
        events: [T,N] binary (source events)
        target_errors: [T,N] binary (target impact indicator; can reuse same event type)
    Returns:
        impact: [N,N]
          impact[i->j] = P(target_error_j within horizon | event_i at t) - P(target_error_j)
    """
    T, N = events.shape
    base = np.mean(target_errors, axis=0)  # [N]

    impact = np.zeros((N, N), dtype=np.float32)
    for i in range(N):
        t_events = np.where(events[:, i] == 1)[0]
        if len(t_events) == 0:
            continue
        for j in range(N):
            hit = 0
            total = 0
            for t in t_events:
                t2 = min(T, t + horizon_steps + 1)
                total += 1
                if np.any(target_errors[t:t2, j] == 1):
                    hit += 1
            cond = hit / max(total, 1)
            impact[i, j] = float(cond - base[j])
    return impact


# ---------------------------
# Plotting helpers
# ---------------------------

def plot_heatmap(mat: np.ndarray, title: str, xlabel: str, ylabel: str,
                 xticks: List[str], yticks: List[str], out_path: str,
                 vmin: Optional[float] = None, vmax: Optional[float] = None) -> None:
    """Save a heatmap to disk."""
    plt.figure(figsize=(8, 6))
    plt.imshow(mat, aspect="auto", vmin=vmin, vmax=vmax)
    plt.colorbar()
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(np.arange(len(xticks)), xticks, rotation=45, ha="right")
    plt.yticks(np.arange(len(yticks)), yticks)
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


def plot_nri_graph(edge_probs: np.ndarray, names: List[str], out_path: str, thresh: float = 0.3) -> None:
    """Plot a directed graph of inferred influences (edges above `thresh`)."""
    N = len(names)
    G = nx.DiGraph()
    for i in range(N):
        G.add_node(names[i])
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            w = float(edge_probs[i, j])
            if w >= thresh:
                G.add_edge(names[j], names[i], weight=w)  # j -> i

    if G.number_of_edges() == 0:
        # Still save an empty plot
        plt.figure(figsize=(6, 6))
        plt.title("NRI inferred graph (no edges above threshold)")
        nx.draw(G, with_labels=True)
        plt.tight_layout()
        plt.savefig(out_path, dpi=200)
        plt.close()
        return

    pos = nx.spring_layout(G, seed=0)
    weights = [G[u][v]["weight"] for u, v in G.edges()]
    plt.figure(figsize=(7, 7))
    plt.title("NRI inferred causal influence graph (directed)")
    nx.draw_networkx_nodes(G, pos, node_size=900)
    nx.draw_networkx_labels(G, pos)
    nx.draw_networkx_edges(G, pos, arrowstyle="->", arrowsize=20, width=[2 + 4 * w for w in weights], alpha=0.8)
    e_labels = {(u, v): f"{G[u][v]['weight']:.2f}" for u, v in G.edges()}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=e_labels, font_size=9)
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


def plot_loss_curve(losses: List[float], out_path: str) -> None:
    """Plot and save the NRI training loss curve."""
    plt.figure(figsize=(7, 4))
    plt.plot(losses)
    plt.title("NRI training loss (MSE)")
    plt.xlabel("Training step")
    plt.ylabel("MSE")
    plt.grid(True, linestyle=":")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


def plot_event_probas(
    times: np.ndarray,
    probas: Dict[str, np.ndarray],
    labels: Optional[FailureLabels],
    names: List[str],
    out_dir: str,
    events: Optional[List[str]] = None,
    smooth_window_s: float = 0.5,
) -> None:
    """
    Save one figure per drone with event probability time-series.

    - One subplot per event (readable).
    - Optional smoothing (raw trace kept faint).
    - Optionally overlays the binary ground-truth label as background + step line.
    """
    if events is None:
        preferred = ["collision", "formation_loss", "gnss_degradation", "wind_loss", "suboptimal_traj"]
        events = [e for e in preferred if e in probas] + [e for e in probas.keys() if e not in preferred]

    T, N = next(iter(probas.values())).shape
    if len(times) >= 2:
        dt = float(np.median(np.diff(times)))
    else:
        dt = 0.1
    win = max(1, int(round(smooth_window_s / max(dt, 1e-6))))
    kernel = np.ones(win, dtype=np.float32) / float(win)

    def smooth(x: np.ndarray) -> np.ndarray:
        if win <= 1:
            return x
        return np.convolve(x, kernel, mode="same")

    for i in range(N):
        fig_h = max(3.0, 1.5 * len(events))
        fig, axes = plt.subplots(len(events), 1, figsize=(11, fig_h), sharex=True)
        if len(events) == 1:
            axes = [axes]

        for k, ev in enumerate(events):
            ax = axes[k]
            y = probas[ev][:, i]
            ys = smooth(y)

            ax.plot(times, ys, linewidth=1.8, label="pred (smoothed)")
            ax.plot(times, y, linewidth=0.8, alpha=0.25, label="pred (raw)")

            if labels is not None and hasattr(labels, ev):
                lab = getattr(labels, ev)[:, i].astype(np.float32)
                ax.fill_between(times, 0.0, 1.0, where=lab > 0.5, step="pre", alpha=0.08)
                ax.plot(times, 0.95 * lab, drawstyle="steps-pre", linewidth=0.9, alpha=0.35, label="label")

            ax.set_ylim(0.0, 1.0)
            ax.set_ylabel(ev, fontsize=9)
            ax.grid(True, linestyle=":", alpha=0.6)

            if k == 0:
                ax.legend(loc="upper right", fontsize=8, ncol=3)

        axes[-1].set_xlabel("time [s]")
        fig.suptitle(f"Event probabilities - {names[i]}", fontsize=12)
        fig.tight_layout(rect=[0, 0, 1, 0.95])
        fig.savefig(os.path.join(out_dir, f"event_probabilities_{names[i]}.png"), dpi=180)
        plt.close(fig)


def plot_timeseries_per_drone(
    times: np.ndarray,
    series: np.ndarray,
    names: List[str],
    title: str,
    ylabel: str,
    out_path: str,
    y_min: Optional[float] = None,
    y_max: Optional[float] = None,
) -> None:
    """Generic helper: one subplot per drone for a [T,N] series."""
    T, N = series.shape
    fig, axes = plt.subplots(N, 1, figsize=(11, max(3.0, 1.6 * N)), sharex=True)
    if N == 1:
        axes = [axes]
    for i in range(N):
        ax = axes[i]
        ax.plot(times, series[:, i], linewidth=1.4)
        ax.set_ylabel(names[i], fontsize=9)
        ax.grid(True, linestyle=":", alpha=0.6)
        if y_min is not None or y_max is not None:
            ax.set_ylim(y_min, y_max)
    axes[-1].set_xlabel("time [s]")
    fig.suptitle(title, fontsize=12)
    fig.text(0.01, 0.5, ylabel, va="center", rotation="vertical", fontsize=10)
    fig.tight_layout(rect=[0.03, 0.02, 1, 0.95])
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_min_distance_global(
    times: np.ndarray,
    pos_gt: np.ndarray,
    collision_dist: float,
    out_path: str,
) -> None:
    """Plot the global minimum pairwise distance between any two drones vs time (GT positions)."""
    dists = compute_pairwise_dists(pos_gt)  # [T,N,N]
    T, N, _ = dists.shape
    for t in range(T):
        np.fill_diagonal(dists[t], np.inf)
    min_global = np.min(dists, axis=(1, 2))  # [T]

    plt.figure(figsize=(11, 4))
    plt.plot(times, min_global, linewidth=1.6)
    plt.axhline(float(collision_dist), linestyle="--", linewidth=1.0, alpha=0.7)
    plt.title("Global minimum inter-drone distance vs time (GT)")
    plt.xlabel("time [s]")
    plt.ylabel("min distance [m]")
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()


def _count_episodes(mask: np.ndarray) -> int:
    """Count contiguous True segments in a 1D boolean array."""
    if mask.size == 0:
        return 0
    m = mask.astype(np.int32)
    starts = (m == 1) & (np.roll(m, 1) == 0)
    starts[0] = (m[0] == 1)
    return int(np.sum(starts))


def compute_run_metrics(logs: SwarmLogs, labels: FailureLabels, swarm_indices: List[int], collision_dist: float) -> Dict:
    """Compute simple, robust, report-friendly metrics from GT logs."""
    T, N = labels.collision.shape

    # Global min distance (GT)
    dists = compute_pairwise_dists(logs.data["gt_pos"])  # [T,N,N]
    for t in range(T):
        np.fill_diagonal(dists[t], np.inf)
    min_global = np.min(dists, axis=(1, 2))  # [T]
    collision_mask = min_global < float(collision_dist)
    collision_episodes = _count_episodes(collision_mask)

    # Swarm formation error stats (swarm only)
    swarm_indices = list(swarm_indices)
    fe = labels.formation_error[:, :]  # [T,N] (0 for independent drones)
    fe_swarm = fe[:, swarm_indices] if len(swarm_indices) > 0 else np.zeros((T, 0), dtype=np.float32)

    speed = labels.speed  # [T,N]

    out = {
        "T": int(T),
        "N": int(N),
        "dt_median": float(np.median(np.diff(logs.times))) if len(logs.times) > 1 else None,
        "min_interdrone_distance_min": float(np.min(min_global)),
        "min_interdrone_distance_p05": float(np.quantile(min_global, 0.05)),
        "collision_steps_frac": float(np.mean(collision_mask)),
        "collision_episodes": int(collision_episodes),
        "swarm_formation_error_mean": float(np.mean(fe_swarm)) if fe_swarm.size else 0.0,
        "swarm_formation_error_p95": float(np.quantile(fe_swarm, 0.95)) if fe_swarm.size else 0.0,
        "swarm_formation_error_max": float(np.max(fe_swarm)) if fe_swarm.size else 0.0,
    }

    # Per-drone metrics
    per = []
    for i, name in enumerate(logs.drone_names):
        per.append({
            "drone": name,
            "speed_mean": float(np.mean(speed[:, i])),
            "speed_p95": float(np.quantile(speed[:, i], 0.95)),
            "speed_max": float(np.max(speed[:, i])),
            "formation_error_mean": float(np.mean(fe[:, i])),
            "formation_error_p95": float(np.quantile(fe[:, i], 0.95)),
            "collision_steps_frac": float(np.mean(labels.collision[:, i] > 0.5)),
            "gnss_deg_steps_frac": float(np.mean(labels.gnss_degradation[:, i] > 0.5)),
            "wind_loss_steps_frac": float(np.mean(labels.wind_loss[:, i] > 0.5)),
            "suboptimal_steps_frac": float(np.mean(labels.suboptimal_traj[:, i] > 0.5)),
        })
    out["per_drone"] = per
    return out


def plot_event_timeline(times: np.ndarray, labels: FailureLabels, names: List[str], out_path: str,
                        events: Optional[List[str]] = None) -> None:
    """Binary timeline heatmap per event: rows=drones, x=time."""
    if events is None:
        events = ["collision", "formation_loss", "gnss_degradation", "wind_loss", "suboptimal_traj"]
    fig, axes = plt.subplots(len(events), 1, figsize=(12, max(3.5, 1.6 * len(events))), sharex=True)
    if len(events) == 1:
        axes = [axes]
    t0 = float(times[0])
    t1 = float(times[-1])
    for k, ev in enumerate(events):
        ax = axes[k]
        mat = getattr(labels, ev).T.astype(np.float32)  # [N,T]
        ax.imshow(mat, aspect="auto", interpolation="nearest",
                  extent=[t0, t1, -0.5, len(names) - 0.5], origin="lower")
        ax.set_yticks(np.arange(len(names)))
        ax.set_yticklabels(names, fontsize=8)
        ax.set_ylabel(ev, fontsize=9)
        ax.grid(False)
    axes[-1].set_xlabel("time [s]")
    fig.suptitle("Event timeline (binary labels)", fontsize=12)
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_signal_timeseries(times: np.ndarray, series: np.ndarray, names: List[str], title: str, ylabel: str, out_path: str) -> None:
    """One subplot per drone for a [T,N] signal."""
    plot_timeseries_per_drone(times, series, names, title=title, ylabel=ylabel, out_path=out_path)


def save_matrix_csv(mat: np.ndarray, row_names: List[str], col_names: List[str], out_path: str) -> None:
    """Save a matrix as a CSV with row/column labels."""
    df = pd.DataFrame(mat, index=row_names, columns=col_names)
    df.to_csv(out_path)


# ---------------------------
# Main pipeline
# ---------------------------

def run_pipeline(args: argparse.Namespace) -> Dict:
    """Run the full analysis pipeline and save outputs."""
    ensure_dir(args.output_dir)

    logs = load_swarm_logs(args.log_dir, downsample=args.downsample)
    names = logs.drone_names
    N = len(names)
    print(f"[Load] N={N} drones, T={len(logs.times)} steps, dt≈{logs.dt:.4f}s, downsample={args.downsample}")

    swarm_idxs = _parse_indices(args.swarm_indices, N)
    ind_idxs = _parse_indices(args.independent_indices, N)

    labels = detect_failures(
        logs,
        leader_index=args.leader_index,
        collision_dist=args.collision_dist,
        formation_thresh=args.formation_thresh,
        gnss_quantile=args.gnss_quantile,
        wind_quantile=args.wind_quantile,
        suboptimal_quantile=args.suboptimal_quantile,
        suboptimal_persist_steps=args.suboptimal_persist,
        event_persist_steps=args.event_persist,
        swarm_indices=swarm_idxs,
        independent_indices=ind_idxs,
        target_jump_thresh=args.target_jump_thresh,
        smooth_window=args.smooth_window,
    )

    # ------------------ Report-friendly GT outputs (recommended) ------------------
    out = args.output_dir

    metrics = compute_run_metrics(logs, labels, swarm_indices=swarm_idxs, collision_dist=float(args.collision_dist))
    # Save metrics (JSON + CSV)
    with open(os.path.join(out, "metrics_summary.json"), "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)
    pd.DataFrame(metrics.get("per_drone", [])).to_csv(os.path.join(out, "metrics_per_drone.csv"), index=False)

    # GT-derived time-series (always useful)
    plot_timeseries_per_drone(
        logs.times,
        labels.formation_error,
        names,
        title="Formation error per drone (computed only within swarm: indices in --swarm_indices)",
        ylabel="formation error [m]",
        out_path=os.path.join(out, "formation_error_timeseries.png"),
        y_min=0.0,
    )
    plot_timeseries_per_drone(
        logs.times,
        labels.speed,
        names,
        title="Speed per drone vs time (GT velocity)",
        ylabel="speed [m/s]",
        out_path=os.path.join(out, "speed_timeseries.png"),
        y_min=0.0,
    )
    plot_min_distance_global(
        logs.times,
        logs.data["gt_pos"],
        collision_dist=float(args.collision_dist),
        out_path=os.path.join(out, "min_interdrone_distance_gt.png"),
    )

    # Binary event timeline (often more interpretable than many matrices)
    plot_event_timeline(logs.times, labels, names, out_path=os.path.join(out, "event_timeline.png"))

    # Exogenous signal timelines (useful for causal narratives / ablations)
    plot_signal_timeseries(
        logs.times,
        logs.data["gnss_error_mag"],
        names,
        title="GNSS error magnitude per drone",
        ylabel="gnss_error_mag [m]",
        out_path=os.path.join(out, "gnss_error_timeseries.png"),
    )
    plot_signal_timeseries(
        logs.times,
        logs.data["wind_mag"],
        names,
        title="Wind magnitude per drone",
        ylabel="wind_mag [m/s]",
        out_path=os.path.join(out, "wind_mag_timeseries.png"),
    )

    if getattr(args, "mode", "lite") == "lite":
        print("[Mode] lite: skipping NRI / Granger / root-cause / impact matrices. Use --mode full to enable them.")
        return metrics

    # Build dataset for NRI
    ds = build_sequence_dataset(logs, use_measured=args.use_measured)

    # Train NRI
    nri_res = train_nri(
        dataset=ds,
        n_nodes=N,
        seq_len=args.seq_len,
        n_edge_types=args.n_edge_types,
        hidden=args.hidden,
        dropout=args.dropout,
        batch_size=args.batch_size,
        nri_steps=args.nri_steps,
        lr=args.lr,
        tau_start=args.tau_start,
        tau_end=args.tau_end,
        tau_anneal_steps=args.tau_anneal_steps,
        max_train_windows=args.max_train_windows,
        device=args.device,
        torch_threads=args.torch_threads,
        seed=args.seed,
        verbose_every=args.verbose_every,
    )

    # --- Proximity-weighted edges (physics-aware gating) ---
    proximity_frac = compute_proximity_fraction(logs.data["gt_pos"], args.proximity_radius)
    edge_probs_raw = nri_res.edge_probs.astype(np.float32)
    edge_probs_effective = (edge_probs_raw * proximity_frac).astype(np.float32)

    # ------------------ save matrices ------------------
    out = args.output_dir

    # "edge_probs_one_minus" keeps prior naming; it is (1 - edge_probs_raw) here, used for debugging/visualization
    edge_probs_one_minus = (1.0 - edge_probs_raw).astype(np.float32)

    np.save(os.path.join(out, "nri_edge_probs_raw.npy"), edge_probs_raw)
    np.save(os.path.join(out, "nri_edge_probs.npy"), edge_probs_one_minus)
    np.save(os.path.join(out, "nri_proximity_fraction.npy"), proximity_frac)
    np.save(os.path.join(out, "nri_edge_effective.npy"), edge_probs_effective)

    save_matrix_csv(edge_probs_raw, row_names=names, col_names=names, out_path=os.path.join(out, "nri_edge_probs_raw.csv"))
    save_matrix_csv(edge_probs_one_minus, row_names=names, col_names=names, out_path=os.path.join(out, "nri_edge_probs.csv"))
    save_matrix_csv(proximity_frac, row_names=names, col_names=names, out_path=os.path.join(out, "nri_proximity_fraction.csv"))
    save_matrix_csv(edge_probs_effective, row_names=names, col_names=names, out_path=os.path.join(out, "nri_edge_effective.csv"))

    # ------------------ figures ------------------
    plot_loss_curve(nri_res.nri_loss_curve, os.path.join(out, "nri_training_loss.png"))

    # Edge visualizations:
    # 1) Main heatmap requested: 1 - raw
    plot_heatmap(
        edge_probs_one_minus,
        title="1 - NRI interaction score (receiver i, sender j)",
        xlabel="sender j",
        ylabel="receiver i",
        xticks=names,
        yticks=names,
        out_path=os.path.join(out, "nri_edge_probs_heatmap.png"),
        vmin=0.0,
        vmax=1.0,
    )

    # 2) Raw heatmap (debug)
    plot_heatmap(
        edge_probs_raw,
        title="NRI inferred interaction score RAW (receiver i, sender j)",
        xlabel="sender j",
        ylabel="receiver i",
        xticks=names,
        yticks=names,
        out_path=os.path.join(out, "nri_edge_probs_raw_heatmap.png"),
        vmin=0.0,
        vmax=1.0,
    )

    # 3) Proximity fraction heatmap
    plot_heatmap(
        proximity_frac,
        title=f"Proximity fraction P(dist<{args.proximity_radius:.2f}m) (receiver i, sender j)",
        xlabel="sender j",
        ylabel="receiver i",
        xticks=names,
        yticks=names,
        out_path=os.path.join(out, "nri_proximity_fraction_heatmap.png"),
        vmin=0.0,
        vmax=1.0,
    )

    # 4) Effective edges: raw * proximity
    plot_heatmap(
        edge_probs_effective,
        title="Effective interaction score = RAW * proximity (receiver i, sender j)",
        xlabel="sender j",
        ylabel="receiver i",
        xticks=names,
        yticks=names,
        out_path=os.path.join(out, "nri_edge_effective_heatmap.png"),
        vmin=0.0,
        vmax=1.0,
    )

    # High-level summary for reporting
    summary = {
        "log_dir": args.log_dir,
        "output_dir": args.output_dir,
        "n_drones": N,
        "n_steps": int(len(logs.times)),
        "dt": logs.dt,
        "nri": {
            "seq_len": args.seq_len,
            "n_edge_types": args.n_edge_types,
            "hidden": args.hidden,
            "nri_steps": args.nri_steps,
            "final_train_mse": float(np.mean(nri_res.nri_loss_curve[-50:])) if len(nri_res.nri_loss_curve) >= 50 else float(np.mean(nri_res.nri_loss_curve)),
        },
        "detection": {
            "collision_dist": args.collision_dist,
            "formation_thresh": args.formation_thresh,
            "gnss_quantile": args.gnss_quantile,
            "wind_quantile": args.wind_quantile,
            "suboptimal_quantile": args.suboptimal_quantile,
            "event_persist": args.event_persist,
            "suboptimal_persist": args.suboptimal_persist,
            "smooth_window": args.smooth_window,
            "target_jump_thresh": args.target_jump_thresh,
            "swarm_indices": swarm_idxs,
            "independent_indices": ind_idxs,
        },
        "proximity_radius": args.proximity_radius,
        "top_edges_effective": top_edges_from_matrix(edge_probs_effective, names, k=10),
        "top_edges_raw": top_edges_from_matrix(edge_probs_raw, names, k=10),
    }

    with open(os.path.join(out, "summary_report.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(f"[Done] Outputs saved to: {os.path.abspath(out)}")
    return summary


def top_edges_from_matrix(mat: np.ndarray, names: List[str], k: int = 10) -> List[Dict]:
    """Return the top-k directed edges (by weight) from a square matrix."""
    N = len(names)
    edges = []
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            edges.append((float(mat[i, j]), j, i))  # w, sender, receiver
    edges.sort(reverse=True, key=lambda x: x[0])
    out = []
    for w, j, i in edges[:k]:
        out.append({"sender": names[j], "receiver": names[i], "weight": w})
    return out


def build_argparser() -> argparse.ArgumentParser:
    """Build the CLI argument parser."""
    p = argparse.ArgumentParser(description="Causal analysis (NRI + event root cause) for UxS swarm logs.")

    p.add_argument("--log_dir", type=str, default="logs", help="Directory containing drone_*.csv logs.")
    p.add_argument("--output_dir", type=str, default="causal_out", help="Output directory for matrices and figures.")
    p.add_argument("--mode", type=str, default="lite", choices=["lite", "full"],
                   help="Compute mode. lite: GT-based metrics & timelines. full: also NRI/Granger/impact matrices.")

    # Sampling / speed
    p.add_argument("--downsample", type=int, default=1, help="Downsample logs by keeping every k-th row.")
    p.add_argument("--seed", type=int, default=0, help="Random seed.")
    p.add_argument("--device", type=str, default="cpu", help="cpu or cuda (if available).")
    p.add_argument("--torch_threads", type=int, default=1, help="Number of CPU threads for PyTorch (use 1 to avoid overhead on small tensors).")

    # Failure detection thresholds
    p.add_argument("--leader_index", type=int, default=0, help="Leader drone index for formation reference.")
    p.add_argument("--collision_dist", type=float, default=0.6, help="Collision distance threshold [m].")
    p.add_argument("--formation_thresh", type=float, default=1.0, help="Formation loss threshold [m].")
    p.add_argument("--gnss_quantile", type=float, default=0.95, help="Quantile threshold for GNSS degradation.")
    p.add_argument("--wind_quantile", type=float, default=0.95, help="Quantile threshold for wind loss.")
    p.add_argument("--suboptimal_quantile", type=float, default=0.95, help="Quantile for suboptimal trajectory.")
    p.add_argument("--suboptimal_persist", type=int, default=5, help="Min consecutive steps for suboptimal label.")

    # Mission configuration (explicit)
    p.add_argument("--swarm_indices", type=str, default="0,1,2", help="Comma-separated indices for swarm drones (formation computed only within this set).")
    p.add_argument("--independent_indices", type=str, default="3", help="Comma-separated indices for independent drones (excluded from formation_loss).")

    # Label stability (reduce spikes)
    p.add_argument("--event_persist", type=int, default=5, help="Min consecutive steps for GNSS/wind labels (persistence).")
    p.add_argument("--smooth_window", type=int, default=5, help="Rolling median window for tracking error smoothing.")
    p.add_argument("--target_jump_thresh", type=float, default=20.0, help="Target jump threshold [m/step] to ignore for suboptimal_traj.")

    # Physics-aware interpretation of NRI edges
    p.add_argument("--proximity_radius", type=float, default=2.0, help="Radius [m] used to gate NRI edges by proximity (edge_effective = edge_raw * P(dist<R)).")

    # NRI training params
    p.add_argument("--use_measured", action="store_true", help="Use measured positions (EKF) instead of ground truth for NRI.")
    p.add_argument("--seq_len", type=int, default=30, help="Sequence length (window) for NRI.")
    p.add_argument("--n_edge_types", type=int, default=3, help="Number of edge types (type 0 assumed no-edge).")
    p.add_argument("--hidden", type=int, default=128, help="Hidden dimension for NRI.")
    p.add_argument("--dropout", type=float, default=0.0, help="Dropout probability.")
    p.add_argument("--batch_size", type=int, default=64, help="Batch size for NRI training.")
    p.add_argument("--nri_steps", type=int, default=2000, help="Training steps for NRI.")
    p.add_argument("--max_train_windows", type=int, default=5000, help="Max sampled windows for training pool.")
    p.add_argument("--lr", type=float, default=3e-4, help="Learning rate for NRI.")
    p.add_argument("--tau_start", type=float, default=1.0, help="Initial Gumbel-Softmax temperature.")
    p.add_argument("--tau_end", type=float, default=0.5, help="Final Gumbel-Softmax temperature.")
    p.add_argument("--tau_anneal_steps", type=int, default=1500, help="Anneal steps for tau.")
    p.add_argument("--verbose_every", type=int, default=100, help="Print NRI training status every k steps.")
    p.add_argument("--graph_thresh", type=float, default=0.3, help="Edge threshold for graph visualization.")

    # Event models / causal explanations
    p.add_argument("--event_lag", type=int, default=1, help="Lag (in timesteps) for event prediction features.")
    p.add_argument("--max_events_to_explain", type=int, default=2000, help="Cap number of positive event instances to explain per event.")
    p.add_argument("--granger_maxlag", type=int, default=5, help="Max lag for Granger tests.")
    p.add_argument("--impact_horizon", type=int, default=10, help="Horizon steps for systemic impact estimation.")

    return p


def main():
    """CLI entrypoint."""
    args = build_argparser().parse_args()
    run_pipeline(args)


if __name__ == "__main__":
    main()
